/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.prjmanutencao.telas;

import com.prjmanutencao.dal.ModuloConexao;
import java.sql.*;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Fábio
 */
public class TelaAcesso extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    JLabel ace = new JLabel();

    String data;
    public static String nome = null;
    JTable DefaultTableModel = null;

//    int id2 = 0;
    /**
     * Creates new form TelaPrevMensal
     */
    public TelaAcesso() {
        initComponents();
        conexao = ModuloConexao.conector();
        consultaAcesso();

        JTableHeader header = tblAcesso.getTableHeader();
        DefaultTableCellRenderer centralizado = (DefaultTableCellRenderer) header.getDefaultRenderer();
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);

    }

    class JlabelGradient extends JLabel {

        
        protected void paintComponent(Graphics estilo) {

            Graphics2D g2d = (Graphics2D) estilo;
            int width = getWidth();
            int height = getHeight();
            Color cor1 = new Color(158, 158, 158, 90);
            Color cor2 = new Color(255, 255, 255);
            GradientPaint gp = new GradientPaint(0, 0, cor1, 0, height, cor2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);

        }
    }

    private void consultaAcesso() {

        String sql = "select a.id_ace as 'N° Acesso', a.ip_maqui as 'N° IP', a.nome_maqui as 'Máquina', a.data_entr as 'Entrada', a.data_said as 'Saída', u.iduser as 'R.E', u.nome_usuario as 'Nome' from acesso a inner join  usuarios u on a.iduser = u.iduser order by a.id_ace asc";
        try {
            pst = conexao.prepareStatement(sql);
            rs = pst.executeQuery();
            tblAcesso.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private void pesquisarAcesso() {
        data = null;

        java.util.Date pega = cadPesAce.getDate();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        this.data = formato.format(pega);

        String sql = "select a.id_ace as 'N° Acesso', a.ip_maqui as 'N° IP', a.nome_maqui as 'Máquina', a.data_entr as 'Entrada', a.data_said as 'Saída', u.iduser as 'R.E', u.nome_usuario as 'Nome' from acesso a inner join  usuarios u on a.iduser = u.iduser where a.data_entr like ?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, data + "%");
            rs = pst.executeQuery();
            tblAcesso.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void setarAcesso() {

        int setar = tblAcesso.getSelectedRow();
        txtNumAce.setText(tblAcesso.getModel().getValueAt(setar, 0).toString());
        txtRegUsu.setText(tblAcesso.getModel().getValueAt(setar, 5).toString());
        txtNomUsu.setText(tblAcesso.getModel().getValueAt(setar, 6).toString());
        consultaAcesso();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        tblAcesso = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cadPesAce = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNumAce = new javax.swing.JTextField();
        jLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNomUsu = new javax.swing.JTextField();
        txtRegUsu = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        JLabel = new JlabelGradient();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Lista de Acessos");
        setPreferredSize(new java.awt.Dimension(1007, 672));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        tblAcesso = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIdex, int colIndex){
                return false;
            }
        };
        tblAcesso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblAcesso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "N° Acesso", "IP da Máquina", "Nome da Máquina", "Entrada", "Saída", "R.E", "Usuário"
            }
        ));
        tblAcesso.getTableHeader().setReorderingAllowed(false);
        tblAcesso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAcessoMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblAcesso);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(42, 126, 910, 340);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lista de Acessos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(320, 50, 310, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/prjmanutencao/icones/48798_file operations_file operations.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(630, 40, 80, 70);

        cadPesAce.getDateEditor().addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent e) {
                if ("date".equals(e.getPropertyName())) {
                    pesquisarAcesso();

                }
            }
        });
        getContentPane().add(cadPesAce);
        cadPesAce.setBounds(120, 66, 140, 28);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102)));
        jPanel1.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("N° Acesso");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(6, 0, 70, 20);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("R.E");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(100, 0, 70, 20);

        txtNumAce.setEditable(false);
        txtNumAce.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtNumAce.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtNumAce);
        txtNumAce.setBounds(10, 20, 64, 24);

        jLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel.setForeground(new java.awt.Color(0, 0, 51));
        jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel.setText("Usuário");
        jPanel1.add(jLabel);
        jLabel.setBounds(54, 42, 70, 20);

        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(310, 520, 110, 14);

        txtNomUsu.setEditable(false);
        txtNomUsu.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtNomUsu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtNomUsu);
        txtNomUsu.setBounds(10, 60, 156, 24);

        txtRegUsu.setEditable(false);
        txtRegUsu.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtRegUsu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtRegUsu);
        txtRegUsu.setBounds(100, 20, 64, 24);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/prjmanutencao/icones/8396426_printer_document_business_office_machine_print.png"))); // NOI18N
        jPanel1.add(jButton1);
        jButton1.setBounds(190, 14, 64, 64);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(670, 500, 280, 90);

        btnVoltar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(0, 0, 51));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(120, 100, 85, 23);
        getContentPane().add(JLabel);
        JLabel.setBounds(0, 0, 1000, 650);

        setBounds(0, 0, 1007, 672);
    }// </editor-fold>//GEN-END:initComponents

    private void tblAcessoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAcessoMouseClicked
        // TODO add your handling code here:
        setarAcesso();

    }//GEN-LAST:event_tblAcessoMouseClicked

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        consultaAcesso();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("C:\\Users\\fabio\\OneDrive\\Área de Trabalho\\NetBeansProjects\\prjManutencao1\\src\\com\\prjmanutencao\\icones\\data.png");
        cadPesAce.setIcon(icon);
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel;
    private javax.swing.JButton btnVoltar;
    private com.toedter.calendar.JDateChooser cadPesAce;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    public static javax.swing.JTable tblAcesso;
    private javax.swing.JTextField txtNomUsu;
    private javax.swing.JTextField txtNumAce;
    private javax.swing.JTextField txtRegUsu;
    // End of variables declaration//GEN-END:variables
}
